CHROMOSOMES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22] 
# CHROMOSOMES: [2] 

STRATA: [1, 2, 3, 4, 6, 7]
# STRATA: [6]

gwasdir: "/hpc/hers_en/shared/gwas2018/main_results"
ref_prefix: "/hpc/hers_en/shared/str_imputation/phasing/panels/df2_subset_N3000_SNP_STR_eh37k_passed"
n_per_batch: 1000
