name: str_imputation
channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.6
  - pandas =1.1.3
  - numpy =1.19.2
  - argparse =1.4.0
  - pyliftover =0.3
  - cyvcf2 =0.30.11
  - snakemake-minimal =5.6.0
  - bcftools =1.3.1
  - r-base =3.6
  - r-tidyverse =1.3.1
  - r-data.table =1.14.0
  - r-r.utils =2.12.2
  - r-vcfr =1.13.0
  - r-rfast =2.0.6
  - beagle =5.1
  - plink =1.90b6.21

